return {
	"tpope/vim-fugitive",
	event = "VeryLazy",
	keys = {
		{ "<leader>gs", "<cmd>Git<cr>", desc = "Git status" },
		{ "<leader>gc", "<cmd>Git commit<cr>", desc = "Git commit" },
		{ "<leader>gp", "<cmd>Git push<cr>", desc = "Git push" },
		{ "<leader>gP", "<cmd>Git pull<cr>", desc = "Git pull" },
		{ "<leader>glc", "<cmd>Git log<cr>", desc = "[G]it [L]ist [C]ommits" },
		{ "<leader>glC", "<cmd>Git log -p<cr>", desc = "[G]it [L]ist [C]ommits (patch)" },
		{ "<leader>glg", "<cmd>Git log --oneline --graph --all<cr>", desc = "[G]it [L]ist [G]raph" },
		{ "<leader>gb", "<cmd>Git blame<cr>", desc = "Git blame" },
		{ "<leader>gd", "<cmd>Gvdiffsplit<cr>", desc = "Git diff" },
		{ "<leader>gD", "<cmd>Gvdiffsplit!<cr>", desc = "Git 3-way diff" },
		{ "<leader>gw", "<cmd>Gwrite<cr>", desc = "Git write" },
		{ "<leader>gh", mode = "n", "<cmd>diffget //2 | diffupdate<cr>", desc = "Git accept target (ours)" },
		{ "<leader>gl", mode = "n", "<cmd>diffget //3 | diffupdate<cr>", desc = "Git accept merge (theirs)" },
		{ "<leader>gh", mode = "x", "'<,'>diffget //2 | diffupdate<cr>", desc = "Git accept target (ours)" },
		{ "<leader>gl", mode = "x", "'<,'>diffget //3 | diffupdate<cr>", desc = "Git accept merge (theirs)" },
	},
}
